#!/usr/bin/env python
# -*- coding: utf-8 -*-

from codeco.processor import Processor

proc = Processor()
proc.create_document(
    'source.py', 'annotations.md',
    title='codeco example #1', out_file='ex1.html',
)
print('[DONE]')
