#!/usr/bin/env python
# -*- coding: utf-8 -*-

from codeco.processor import Processor

proc = Processor()
proc.create_document(
    'source.sh', 'annotations.rst',
    title='codeco example #2', out_file='ex2.html',
    renderer_opts={
        'initial_header_level' : 4
    },
)
print('[DONE]')
