#!/usr/bin/env python

from codeco.processor import Processor

proc = Processor()
proc.create_document(
    'source.sh', 'annotations.rst',
    out_file='ex2.html', renderer_opts={'initial_header_level' : 4}
)
print('[DONE]')
